SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS Host1;
DROP TABLE IF EXISTS Host2;
DROP TABLE IF EXISTS `Event`;
DROP TABLE IF EXISTS Performer;
DROP TABLE IF EXISTS Venue1;
DROP TABLE IF EXISTS Venue2;
DROP TABLE IF EXISTS EventCategory;
DROP TABLE IF EXISTS RegularUser1;
DROP TABLE IF EXISTS RegularUser2;
DROP TABLE IF EXISTS RegularUser3;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS TicketVendor1;
DROP TABLE IF EXISTS TicketVendor2;
DROP TABLE IF EXISTS UserSchedule;
DROP TABLE IF EXISTS HostSchedule;
DROP TABLE IF EXISTS BookedAt;
DROP TABLE IF EXISTS PerformsAt;
DROP TABLE IF EXISTS IsCategory;
DROP TABLE IF EXISTS IsFor;
DROP TABLE IF EXISTS Reserves;
DROP TABLE IF EXISTS Sells;

SET FOREIGN_KEY_CHECKS=1;