SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `host1`;
DROP TABLE IF EXISTS `host2`;
DROP TABLE IF EXISTS `event`;
DROP TABLE IF EXISTS `performer`;
DROP TABLE IF EXISTS `venue1`;
DROP TABLE IF EXISTS `venue2`;
DROP TABLE IF EXISTS `eventcategory`;
DROP TABLE IF EXISTS `regularuser1`;
DROP TABLE IF EXISTS `regularuser2`;
DROP TABLE IF EXISTS `regularuser3`;
DROP TABLE IF EXISTS `ticket`;
DROP TABLE IF EXISTS `ticketvendor1`;
DROP TABLE IF EXISTS `ticketvendor2`;
DROP TABLE IF EXISTS `userschedule`;
DROP TABLE IF EXISTS `hostschedule`;
DROP TABLE IF EXISTS `bookedat`;
DROP TABLE IF EXISTS `performsat`;
DROP TABLE IF EXISTS `iscategory`;
DROP TABLE IF EXISTS `isfor`;
DROP TABLE IF EXISTS `reserves`;
DROP TABLE IF EXISTS `sells`;

SET FOREIGN_KEY_CHECKS=1;